services:
  - type: web
    name: portfolio-server
    env: node
    plan: free
    autoDeploy: true
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node src/index.js"
    healthCheckPath: "/api/health"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: 20.11.1
